apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: dotnet-basic-cuoqmvnf 
  janus-idp.io/tekton: dotnet-basic-cuoqmvnf
  backstage.io/kubernetes-id: dotnet-basic-cuoqmvnf
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: dotnet-basic-cuoqmvnf
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml